### ISSUE TITLE
#街名收集

### ISSUE THREAD

**Issue by tiujejauci** [rime/rime-cantonese#69] opened 2020-06-08 21:50 UTC
### 修改意見

| 字 | 音 | 出處／參考資料 |
|----|----|:-------------------|
| 灰窰角街 |![IMG_20200609_053447](https://user-images.githubusercontent.com/31369434/84082762-01ea0280-a9a6-11ea-8599-42313974f087.JPG)|![mmexport1591464025604](https://user-images.githubusercontent.com/31369434/84083585-8db05e80-a9a7-11ea-9851-72c1df026241.jpg)來源：中原地圖，位置：荃灣

**Comment by tiujejauci** [comment] 2020-06-08 21:51
個模版真係唔識用。。。。

**Comment by laubonghaudoi** [comment] 2020-06-08 21:55
> Android寫issues，個模版真係唔識用。。。。

有冇睇到個 Preview 掣？你修改好之後先唔好發佈住，撳個 Preview 睇下咩效果。而且發佈咗之後都係可以修改嘅。唔該補充一下「問題描述」，就寫目前冇收乜嘢或者邊度錯咗就得。然後如果你有其他音要要求收錄嘅話，一次過喺呢個issue入邊列晒出嚟，唔好諗到一個發一個，會好亂我哋冇得管理。

**Comment by sgalal** [comment] 2020-06-09 02:14
https://www.overview.hk/street/

[香港街道名.txt](https://github.com/rime/rime-cantonese/files/4749526/default.txt)

**Comment by tanxpyox** [comment] 2020-06-09 03:34
> https://www.overview.hk/street/

佢哋All Rights Reserved... :disappointed:

**Comment by szc126** [comment] 2020-06-25 08:11
噉 openstreetmap 呢？

**Comment by szc126** [comment] 2020-06-30 03:48
https://overpass-turbo.eu/

```
[out:csv(
  "name:zh",
  "alt_name:zh",
  "old_name:zh",
  "name:en",
  ::id
)][timeout:25];

//{{geocodeArea:"Tsim Sha Tsui"}}->.mySearchArea;
relation(913110);out;map_to_area->.mySearchArea;
(
  way["highway"]["name:zh"](area.mySearchArea);
)->.myWays;

.myWays out tags;
```

**Comment by tanxpyox** [comment] 2020-06-30 05:15
唔知佢授權條款係咩呢

**Comment by szc126** [comment] 2020-06-30 06:56
係openstreetmap嘅數據→https://www.openstreetmap.org/copyright

>OpenStreetMap® is open data, licensed under the Open Data Commons Open Database License (ODbL) by the OpenStreetMap Foundation (OSMF).
>You are free to copy, distribute, transmit and adapt our data, as long as you credit OpenStreetMap and its contributors. If you alter or build upon our data, you may distribute the result only under the same licence.

**Comment by szc126** [comment] 2020-07-06 04:56
啱啱發現咗香港政府也有發佈個「街道名稱」表→https://www.landsd.gov.hk/mapping/tc/download/psi/opendata.htm

**Comment by tiujejauci** [comment] 2020-08-15 14:12
| 字 | 音 | 出處／參考資料 |
|----|----|-------------------|
|莫里茲大道|![image](https://user-images.githubusercontent.com/31369434/90139909-91979d00-ddab-11ea-85b8-53a2d6655450.png)|![image](https://user-images.githubusercontent.com/31369434/90139491-06b6a280-ddab-11ea-8375-04709444096f.png)來源：[Google地圖](https://www.google.com/maps/place/%E9%A6%99%E6%B8%AF%E5%8F%A4%E6%B4%9E%E8%8E%AB%E9%87%8C%E8%8C%B2%E5%A4%A7%E9%81%93/@22.50136,114.0989833,17z/data=!3m1!4b1!4m5!3m4!1s0x3403f66126d34b17:0xf87872cdcfa3e16e!8m2!3d22.50136!4d114.101172)，位置：上水

**Comment by tanxpyox** [comment] 2020-08-15 14:35
Duplicate of #76

**Closed** 2020-08-15 16:40 UTC
Labels: dict
